using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

public class ANN{

	public int numInputs;
	public int numOutputs;
	public int numHidden;
	public int numNPerHidden;
	public double alpha;
	List<Layer> layers = new List<Layer>();

    /**
     * Constructs and initializes a new ANN
     * @param nI - number of inputs
     * @param nO - number of outputs
     * @param nH - number of hidden layers
     * @param nPH - number of neurons per hidden layer
     * @param a - alpha
     */
    public ANN(int nI, int nO, int nH, int nPH, double a)
	{
		numInputs = nI;
		numOutputs = nO;
		numHidden = nH;
		numNPerHidden = nPH;
		alpha = a;

		if(numHidden > 0)
		{
			layers.Add(new Layer(numNPerHidden, numInputs));

			for(int i = 0; i < numHidden-1; i++)
			{
				layers.Add(new Layer(numNPerHidden, numNPerHidden));
			}

			layers.Add(new Layer(numOutputs, numNPerHidden));
		}
		else
		{
			layers.Add(new Layer(numOutputs, numInputs));
		}
	}

    /**
     * Calculate and return the output of the ANN with given inputs
     * and adjust the weights according to the difference
     * between expected output and actual output
     * @param inputValues - the given input values
     * @param desiredOutput - the correct output (we want the actual output to be as close as possible)
     * @return the output of the ANN
     * */
	public List<double> Train(List<double> inputValues, List<double> desiredOutput)
	{
		List<double> outputValues = new List<double>();
		outputValues = CalcOutput(inputValues, desiredOutput);
		UpdateWeights(outputValues, desiredOutput);
		return outputValues;
	}

    /**
     * Calculate and return a list representing the outputs of the ANN
     * from given input values
     * @param inputValues - the given input values
     * @param desiredOutput - the correct output (we want the actual output to be as close as possible)
     * @return the output of the ANN
     * */
	public List<double> CalcOutput(List<double> inputValues, List<double> desiredOutput)
	{
		List<double> inputs = new List<double>();
		List<double> outputValues = new List<double>();
		int currentInput = 0;

		if(inputValues.Count != numInputs)
		{
			Debug.Log("ERROR: Number of Inputs must be " + numInputs);
			return outputValues;
		}

		inputs = new List<double>(inputValues);
		for(int i = 0; i < numHidden + 1; i++)
		{
				if(i > 0)
				{
					inputs = new List<double>(outputValues);
				}
				outputValues.Clear();

				for(int j = 0; j < layers[i].numNeurons; j++)
				{
					double N = 0;
					layers[i].neurons[j].inputs.Clear();

					for(int k = 0; k < layers[i].neurons[j].numInputs; k++)
					{
					    layers[i].neurons[j].inputs.Add(inputs[currentInput]);
						N += layers[i].neurons[j].weights[k] * inputs[currentInput];
						currentInput++;
					}

					N -= layers[i].neurons[j].bias;

					if(i == numHidden)
						layers[i].neurons[j].output = ActivationFunctionO(N);
					else
						layers[i].neurons[j].output = ActivationFunction(N);
					
					outputValues.Add(layers[i].neurons[j].output);
					currentInput = 0;
				}
		}
		return outputValues;
	}

    /**
     * Returns a string representing this ANN's weights
     * @return the string representation
     */
	public string PrintWeights()
	{
		string weightStr = "";
		foreach(Layer l in layers)
		{
			foreach(Neuron n in l.neurons)
			{
				foreach(double w in n.weights)
				{
					weightStr += w + ",";
				}
			}
		}
		return weightStr;
	}

    /**
     * Load weight values from a given weight string
     * generated by the PrintWeights() function
     * @param weightStr - the given string in the correct format
     */
	public void LoadWeights(string weightStr)
	{
		if(weightStr == "") return;
		string[] weightValues = weightStr.Split(',');
		int w = 0;
		foreach(Layer l in layers)
		{
			foreach(Neuron n in l.neurons)
			{
				for(int i = 0; i < n.weights.Count; i++)
				{
					n.weights[i] = System.Convert.ToDouble(weightValues[w]);
					w++;
				}
			}
		}
	}
	
    /**
     * Update the ANN's weights by calculating the error value
     * which is the difference between the desired output and the actual output
     * and adjust the ANN's weights accordingly, using the backpropagation method
     * @param outputs - the actual outputs
     * @param desiredOutput - the desired/correct output
     */
	void UpdateWeights(List<double> outputs, List<double> desiredOutput)
	{
		double error;
		for(int i = numHidden; i >= 0; i--) //we go backwards - the backpropagation method
		{
			for(int j = 0; j < layers[i].numNeurons; j++)
			{
				if(i == numHidden) //first time in for-loop
				{
                    //calculate the error value
					error = desiredOutput[j] - outputs[j];

                    /*calculate the layer's error gradient using a mathematic gradient function
                     * we use this for the ANN's backpropagating approach
                     * notice how when error = 0, errorGradient = 0 as well
                     */
					layers[i].neurons[j].errorGradient = outputs[j] * (1-outputs[j]) * error;
				}
				else
				{
                    /*here we use the neuron's output instead of the final output because in back-propagation
                     * we start from the final layer of the ANN (which gives the final output)
                     * and we're going backwards to adjust each neuron individually
                     * to minimize the SSE (sum-squared error), which is the ambition of any ANN
                     */
					layers[i].neurons[j].errorGradient = layers[i].neurons[j].output * (1-layers[i].neurons[j].output);
					double errorGradSum = 0;
					for(int p = 0; p < layers[i+1].numNeurons; p++)
					{
						errorGradSum += layers[i+1].neurons[p].errorGradient * layers[i+1].neurons[p].weights[j];
					}
					layers[i].neurons[j].errorGradient *= errorGradSum;
				}	
				for(int k = 0; k < layers[i].neurons[j].numInputs; k++)
				{
					if(i == numHidden)
					{
						error = desiredOutput[j] - outputs[j];
                        //here we actually adjust the weights - using the error value (final error)
						layers[i].neurons[j].weights[k] += alpha * layers[i].neurons[j].inputs[k] * error;
					}
					else
					{
                        //and here we are adjusting the weights - using the neuron's error value (neuron-specific)
						layers[i].neurons[j].weights[k] += alpha * layers[i].neurons[j].inputs[k] * layers[i].neurons[j].errorGradient;
					}
				}
                //bias / threshold adjustment
				layers[i].neurons[j].bias += alpha * -1 * layers[i].neurons[j].errorGradient;
			}

		}

	}

	double ActivationFunction(double value)
	{
		return TanH(value);
	}

	double ActivationFunctionO(double value)
	{
		return TanH(value);
	}

	double TanH(double value)
	{
        //double k = (double) System.Math.Exp(-2*value);
        //return 2 / (1.0f + k) - 1;
        return Math.Tanh(value);
	}

	double Sigmoid(double value) 
	{
    	double k = (double) System.Math.Exp(value);
    	return k / (1.0f + k);
	}
}
